# Generated by Django 4.2.20 on 2025-03-27 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('address', models.TextField(verbose_name='Адрес доставки')),
                ('delivery_time', models.DateTimeField(verbose_name='Дата и время доставки')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('is_consultation', models.BooleanField(default=False, verbose_name='Нужна консультация')),
                ('bouquet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.bouquet', verbose_name='Букет')),
            ],
        ),
    ]
