# Generated by Django 5.1.7 on 2025-03-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_consultationrequest_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='bouquet',
            name='color',
            field=models.CharField(choices=[('Белый', 'Белый'), ('Розовый', 'Розовый'), ('Красный', 'Красный')], default='Розовый', max_length=50, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='bouquet',
            name='price_category',
            field=models.CharField(choices=[('~500', '~500'), ('~1000', '~1000'), ('~2000', '~2000'), ('Больше', 'Больше'), ('Не важно', 'Не важно')], default='~1000', max_length=50, verbose_name='Ценовая категория'),
        ),
    ]
