# Generated by Django 5.1.7 on 2025-03-31 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_bouquet_color_bouquet_price_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrequest',
            name='name',
            field=models.CharField(blank=True, default='неизвестно', max_length=100, verbose_name='Имя клиента'),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telegram username'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, default='не указан', max_length=30, verbose_name='Телефон клиента'),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='phone',
            field=models.CharField(blank=True, default='не указан', max_length=30, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, default='не указано', max_length=100, verbose_name='Имя клиента'),
        ),
    ]
