# Generated by Django 5.1.7 on 2025-04-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_consultationrequest_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bouquet',
            name='occasion',
            field=models.CharField(blank=True, choices=[('День рождения', 'День рождения'), ('Свадьба', 'Свадьба'), ('Школа', 'Школа'), ('Без повода', 'Без повода'), ('Другой', 'Другой')], default='', help_text='Например: День рождения, Свадьба и т.д.', max_length=50, verbose_name='Повод'),
        ),
    ]
